### ISSUE TITLE
Rewrite tests in our test directory to use our Arquillian connector where possible

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1004]

**Comment by manorrock** [comment]
Go to https://github.com/javaee-samples/javaee7-samples for some example usage of our Arquillian connector

**Comment by Thihup** [comment]
For now we've a lot of tests using the Piranha embedded that can be used as example as well. 
Should we just rewrite them or create new tests equally in functionality but using Arquillian?

**Comment by manorrock** [comment]
Piranha Embedded gets enough testing because of being used in unit testing. So I would like to the tests in the test directory to be rewritten as Arquillian tests and thus enlarge our testing of Piranha Micro

**Comment by manorrock** [comment]
@Thihup Did I give you enough information?

**Comment by Thihup** [comment]
@manorrock Sure!
I was rewriting some tests, however, most of the tests that I tried to rewrite (Jersey, for instance) fail because the CDI tries to inject where isn't supposed to inject.
I was trying to figure out how to rework the CDI injection because for now, it passes all classes to Weld manage and some of them aren't supposed to be managed by Weld.
There's only one thing I don't know which way would be better: move the refactored tests to _tests/arquillian_ or refactor in-place.

**Comment by manorrock** [comment]
Mmmm, that sounds like the default extension is doing too much? It sounds like we should not enable CDI by default?  What do you think? @arjantijms

**Comment by Thihup** [comment]
Unfortunately, I think we cannot simply disable the CDI because the whole security implementation depends on it.
