### ISSUE TITLE
Document running Piranha Server using module path

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1104]

**Comment by Thihup** [comment]
Should we add some flag to Piranha Server to change from classpath to module path or fully embrace the module path by now?

We may change to only start the server with the module path by default. I think it is not very risky and very straightforward.
It would change basically from `-jar lib/piranha-server.jar` to `--module-path lib -m cloud.piranha.server`.
The classloading process shouldn't change because the work is all done by our classloaders (like DefaultWebApplicationClassLoader).
We may start with this only change and the next step would be to add the module-info.class to our dependencies (like Tyrus).

As soon as we add the module-info to all dependencies we may use both JLink and JPackage.

**Comment by manorrock** [comment]
Lets make it so the default is modules, but you can opt to use classpath if so desired?
