### ISSUE TITLE
Fix signature TCK test

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#1678]

**Comment by manorrock** [comment]
Unfortunately the last Servlet TCK test run still shows that the test failed 

Look for com/sun/ts/tests/signaturetest/servlet/ServletSigTest.java#signatureTest in the log

**Comment by Thihup** [comment]
Actually, it passed. We need to run the TCK client using Java 8, unfortunately. So it will always fail using the JDK 16, but with JDK 8 it passed :)
I think the next Servlet TCK will allow us to run the client using JDK 11, but it doesn't support running with JDK 16 because they have changed some hierarchy classes. 

Yesterday the run with JDK 8 was failing because the Servlet API was compiling the classes with JDK 16 and the JDK 8 doesn't support JDK 16 classes.

**Comment by manorrock** [comment]
Thanks for the clarification. Maybe we could somehow remove the signature test from the Java 16 run before we start that TCK run? So it does not show as a failing test?

**Comment by Thihup** [comment]
Sure.  For now, we are running the signature test twice. In the beginning, we run just the signature test, and running the full TCK, the signature test is the last one. So there is no need to run it separately :)

**Comment by manorrock** [comment]
Will the Java 16 workflow still run the signature test now? If so is it possible to remove it there altogether (as it will never pass and is then just noise?).

**Comment by Thihup** [comment]
IIRC there is a file to ignore a specific test, however, I don't remember which file it is. Maybe @arjantijms knows?

**Comment by Thihup** [comment]
Seems to be the tck/bin/ts.jtx file
