### ISSUE TITLE
Add JPMS flag to ServerPiranhaBuilder

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha#2010]

**Comment by Thihup** [comment]
I don't know if this is a good issue to say this, but we probably should use other term instead of JPMS, it seems to not be very "accepted": https://twitter.com/mreinhold/status/994669659029999616
Using only "jms" could have some confusion with the JMS spec (now Jakarta Messaging).

I actually don't know what to do here 😅

**Comment by mnriem** [comment]
Well the problem really is that there is no other good term to make sure folks understand what gets enabled. Note that even the JDK mailing list calls it JPMS .... now whether Mark Reinhold likes this or not, it now is its "nom de guerre".
