### ISSUE TITLE
More informations about the project

### ISSUE THREAD

**Issue by Thihup** [piranhacloud/piranha#732]
Hello!

I really liked this project, but I'd like to know more information about it, like some objectives, and I couldn't find anywhere.

I think my major question is: Does this project want to be a servlet container or it wants to be a Jakarta EE Full Profile compatible?

If the objective is to be a Jakarta EE server, do you have any plans soon to add EJB support?  

I'd love to contribute with this project, it looks awesome.

**Comment by manorrock** [comment]
See https://piranha.cloud/

**Comment by arjantijms** [comment]
> If the objective is to be a Jakarta EE server, do you have any plans soon to add EJB support?

Yes, the objective includes being a Jakarta EE server. Likely web-profile+ to start, and if feasible full as well. 

We've been evaluating EJB support, and have looked at using existing somewhat portable EJB implementations such as OpenEJB and the now defunct (but could be revived) EasyBeans.

We're mostly leaning towards implementing EJB as EJB compatible services for CDI, as that is almost certainly the future of EJB anyway. This work was started a while ago, but has been in limbo since. See https://github.com/omnifaces/omniservices

**Comment by Thihup** [comment]
Thanks for the information!

I was looking for a new server like for a long time. 
I'm glad to find this one.

I would like to help build it. Is there any issue that I could take a look? 

Thanks!
