### ISSUE TITLE
Fix CDIForwardTest

### ISSUE THREAD

**Issue by manorrock** [piranhacloud/piranha#858]

**Comment by arjantijms** [comment]
This test in isolation is fine. You can run it in a loop endlessly and it will never ever fail.

In the current setup it fails because a ton of different tests and artefacts are put on the same class path.

There's two solutions:

1. Isolate them all into individual modules
2. Delete them and run https://github.com/javaee-samples/javaee7-samples/tree/master/jaspic

**Comment by Thihup** [comment]
What if we change the default beans.xml from Piranha Micro? Currently, we use an empty to indicate an explicit bean archive. However, I was thinking to change to a "Trimmed Bean Archive". I think this solves this issue and will enable some applications, like Jenkins to not have any exception from wrong injections and startup correctly.
For example: 
```xml
<beans>
    <trim/>
</beans>
```
I'm just not sure what the specs say about using it by default.

**Comment by manorrock** [comment]
We need to make it so both the ServletExtension and Tomcat9Extension will not enable CDI unless someone adds a CDI runtime themselves. The MicroServletExtension which is forwarding looking (assuming CDI will be enabled by default in a future Servlet specification) will have CDI enabled.

**Comment by arjantijms** [comment]
Tests removed
